### ISSUE TITLE
Reproducing results

### ISSUE THREAD

**Issue by magdalenapasternak** [josebeo2016/BTS-Encoder-ASVspoof#6]
Hello,

I am trying to reproduce your steps to preprocess, train, and evaluate your model. 
However, I don't know which codes should be run.

For preprocessing the files, I need Kaldi-style documentation; however, there is no code on how to create such files. Would you mind eitherwhere I can find it (in your repo) or how to create the needed f pointing me to files (utt2spk, wav, scp, etc.)?

Then, for the training model from scratch, which yaml file should reproduce the results from your paper? Also, which code would that be? (what should I run). Similarly, for evaluation.

**Comment by josebeo2016** [comment]
Please find the guideline in asvspoof2021/LA/Baseline-RawNet2-bio. Each yaml file is a variant of different positional correlation encoder. You can try any config as you will. 
note that you don’t need to prepare the kaldi-style format (I guess you are mentioning the biosegment) since it have pre-trained sound segmentation model.

**Comment by magdalenapasternak** [comment]
So I did run the train.sh file from  asvspoof2021/LA/Baseline-RawNet2-bio. 

The provided by you command 'train.sh <batch_size>' with batch size 10 does not work with the error:

```
./train.sh 10
biosegment exist
start training
Finished loading model
Traceback (most recent call last):
  File "main.py", line 246, in <module>
    with open(dir_yaml, 'r') as f_yaml:
FileNotFoundError: [Errno 2] No such file or directory: '10'
```

When running it on empty folder it produces:
```
./train.sh out
biosegment exist
start training
Finished loading model
Traceback (most recent call last):
  File "main.py", line 246, in <module>
    with open(dir_yaml, 'r') as f_yaml:
IsADirectoryError: [Errno 21] Is a directory: 'out'
```
 

When I run it on yaml file
`./train.sh configs/model_config_RawNet_first.yaml`

it looks like it trains the model
How do I evaluate the results?

also, if I want to train and evaluate your model on my own files (different audio dataset) would it be the same process?

**Comment by josebeo2016** [comment]
Oh. That is my mistake of providing a wrong instruction. However, you can first train the model by looking at example in train.sh script.
For evaluating, you can use this code: https://github.com/josebeo2016/BTS-Encoder-ASVspoof/blob/3c3437c65f5a4dca047096e0a7012d007748e00d/asvspoof2021/LA/Baseline-RawNet2-bio/main_for.py#L329
I will update a detail instruction later for other dataset (not asvspoof)

**Comment by magdalenapasternak** [comment]
Thank you for the help.

What command should be run to evaluate the model?

**Comment by magdalenapasternak** [comment]
Thank you so much for your help! Do you know when that code will become available?

**Comment by josebeo2016** [comment]
Sorry that I am a bit busy these days. Please try it for couple of weeks. We will come back to maintain this repo soon.
